#import "../lib/card.typ": card
#card(
    atk: 4000,
    attribute: "dark",
    cardImage: 13331639,
    cardType: "monster",
    def: 4000,
    description: "龙族的融合·同调·超量·灵摆怪兽各1只合计4只\n这张卡不用融合召唤不能特殊召唤。\n①：这张卡特殊召唤的场合发动。对方场上的卡全部破坏。②：这张卡不会被对方的效果破坏，对方不能把这张卡作为效果的对象。③：这张卡战斗破坏对方怪兽时才能发动。从卡组·额外卡组把1只「霸王眷龙」怪兽特殊召唤。④：怪兽区域的这张卡被战斗·效果破坏的场合才能发动。这张卡在自己的灵摆区域放置。",
    frameType: "fusion-pendulum",
    id: 13331639,
    level: 12,
    name: "霸王龙 扎克",
    pendulumDescription: "①：只要这张卡在灵摆区域存在，对方不能把场上的融合·同调·超量怪兽的效果发动。②：1回合1次，抽卡阶段以外从卡组有卡加入对方手卡时才能发动。那些卡破坏。",
    scale: 12,
    typeline: "【龙族/灵摆/融合/效果】",
)
#card(
    atk: 5000,
    attribute: "earth",
    cardImage: 23288411,
    cardType: "monster",
    def: 5000,
    description: "这张卡不能通常召唤。让这张卡以外的自己的手卡·墓地的「莫忘」怪兽5种类各1只回到卡组·额外卡组的场合才能从手卡·墓地特殊召唤。\n①：自己场上没有其他怪兽存在的场合，这张卡可以向对方怪兽全部各作1次攻击。②：1回合1次，对方把魔法·陷阱·怪兽的效果发动的场合才能发动。从自己的手卡·墓地把1只「莫忘」怪兽特殊召唤。",
    frameType: "effect",
    id: 23288411,
    level: 11,
    name: "冥骸合龙-莫忘冥地王灵",
    typeline: "【幻龙族/特殊召唤/效果】",
)
#card(
    atk: 2300,
    attribute: "dark",
    cardImage: 86066372,
    cardType: "monster",
    description: "效果怪兽2只以上\n对方不能对应这张卡的效果的发动把效果发动。\n①：这张卡连接召唤的场合，以那1只作为连接素材的连接怪兽为对象才能发动。这张卡的攻击力上升那只怪兽的连接标记数量×1000。②：从自己的场上·墓地把1只连接怪兽除外才能发动。对方场上1张卡破坏。这个回合，自己不能为让「访问码语者」的效果发动而把相同属性的怪兽除外。",
    frameType: "link",
    id: 86066372,
    linkMarkers: (
        bottom: true,
        left: true,
        right: true,
        top: true,
    ),
    linkVal: 4,
    name: "访问码语者",
    typeline: "【电子界族/连接/效果】",
)
#card(
    attribute: "trap",
    cardImage: 8038143,
    cardType: "trap",
    description: "自己场上有「银河眼时空龙」怪兽存在的场合，这张卡的发动从手卡也能用。\n①：自己场上有「银河眼」怪兽存在的场合，连锁2以后才能发动。这张卡的发动时积累的连锁上的全部对方的怪兽的效果·魔法·陷阱卡的发动无效，用这个效果把发动无效的卡在场上存在的场合，那些全部回到卡组。",
    frameType: "trap",
    id: 8038143,
    name: "时空转生",
    // race: "normal",
    race: "counter",
)
