[package]
name = "ygo"
version = "0.1.0"
compiler = "0.14.0"
entrypoint = "lib/mod.typ"
authors = ["arshtyi <arshtyi@foxmail.com>"]
license = "MIT"
description = "Make Yu-Gi-Oh! cards."
repository = "https://github.com/arshtyi/typst-ygo"
categories = ["fun"]
keywords = ["yugioh", "card", "ygo"]
exclude = ["docs/"]
